name: ADSLTCI
description: A new Flutter application for adsl_tci

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  url_launcher: ^5.4.2
  package_info: ^0.4.0+16
  device_info: ^0.4.1+5
  flutter_webview_plugin:
    git:
      url: https://github.com/Alireza271/flutter_webview_plugin.git
  #  flutter_inappwebview:
  #    git:
  #      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
  dio: ^3.0.9
  flutter_svg: ^0.17.1
  fluttertoast: ^3.1.3
  flutter_circular_chart: ^0.1.0
  http: ^0.12.0+4
  html: ^0.14.0+3
  shared_preferences: ^0.5.6+2
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:


  uses-material-design: true


  fonts:
    - family: Samim
      fonts:
        - asset: assets/fonts/Samim_FD.ttf
  assets:
    - assets/icon.png
