import 'package:ADSLTCI/generated/json/base/json_convert_content.dart';
import 'package:ADSLTCI/generated/json/base/json_filed.dart';

class ChangeServiceDitailModelEntity with JsonConvert<ChangeServiceDitailModelEntity> {
	bool ok;
	String who;
	int code;
	String msg;
	ChangeServiceDitailModelResult result;
	String nonce;
}

class ChangeServiceDitailModelResult with JsonConvert<ChangeServiceDitailModelResult> {
	ChangeServiceDitailModelResultService service;
	List<ChangeServiceDitailModelResultBank> banks;
	ChangeServiceDitailModelResultCosts costs;
	@JSONField(name: "KhesaratPrice")
	int khesaratPrice;
}

class ChangeServiceDitailModelResultService with JsonConvert<ChangeServiceDitailModelResultService> {
	@JSONField(name: "Serial")
	String serial;
	@JSONField(name: "ServiceGroup")
	int serviceGroup;
	@JSONField(name: "Name")
	String name;
	@JSONField(name: "IBSName")
	String iBSName;
	@JSONField(name: "Credit")
	int credit;
	@JSONField(name: "FreeCredit")
	int freeCredit;
	@JSONField(name: "ID")
	String iD;
	@JSONField(name: "Price")
	int price;
	@JSONField(name: "Class")
	String xClass;
	@JSONField(name: "AAAClass")
	String aAAClass;
	@JSONField(name: "DayClass")
	int dayClass;
	@JSONField(name: "FreeDays")
	dynamic freeDays;
	@JSONField(name: "SpeedClass")
	int speedClass;
	@JSONField(name: "Special")
	bool special;
	@JSONField(name: "Active")
	bool active;
	@JSONField(name: "Visible")
	bool visible;
	@JSONField(name: "Agent")
	String agent;
	@JSONField(name: "Staff")
	String staff;
	@JSONField(name: "Register")
	String register;
	@JSONField(name: "ForRanje")
	String forRanje;
	@JSONField(name: "ForSharj")
	String forSharj;
	@JSONField(name: "Bestankar")
	String bestankar;
	@JSONField(name: "TownshipRef")
	int townshipRef;
	@JSONField(name: "BranchRef")
	int branchRef;
	@JSONField(name: "Created")
	String created;
	@JSONField(name: "ServiceType")
	String serviceType;
	@JSONField(name: "Ranje")
	String ranje;
	@JSONField(name: "Nasb")
	String nasb;
	@JSONField(name: "Modem")
	String modem;
	@JSONField(name: "Ghest")
	int ghest;
	@JSONField(name: "FreeDay")
	dynamic freeDay;
	@JSONField(name: "FreeGig")
	int freeGig;
	@JSONField(name: "MinPrice")
	int minPrice;
	@JSONField(name: "CalcType")
	dynamic calcType;
	@JSONField(name: "PerGigPrice")
	dynamic perGigPrice;
	@JSONField(name: "Type")
	String type;
	@JSONField(name: "Comment")
	String comment;
	@JSONField(name: "AddIn")
	dynamic addIn;
	@JSONField(name: "ArpoPrice")
	String arpoPrice;
	@JSONField(name: "IsNotMoveable")
	String isNotMoveable;
	@JSONField(name: "FOM")
	dynamic fOM;
	@JSONField(name: "FOY")
	String fOY;
	@JSONField(name: "IsDel")
	String isDel;
	@JSONField(name: "IsMoveAble")
	String isMoveAble;
	@JSONField(name: "IsExtraday")
	String isExtraday;
	@JSONField(name: "IsKart")
	String isKart;
	@JSONField(name: "IsMesi")
	String isMesi;
	@JSONField(name: "HasMobileSim")
	String hasMobileSim;
	@JSONField(name: "NetType")
	String netType;
	@JSONField(name: "AutoRenew")
	String autoRenew;
	@JSONField(name: "InIvr")
	dynamic inIvr;
	@JSONField(name: "IvrRef")
	dynamic ivrRef;
	@JSONField(name: "UssdRef")
	dynamic ussdRef;
	@JSONField(name: "UssdName")
	dynamic ussdName;
	@JSONField(name: "FTTHProductId")
	String fTTHProductId;
	@JSONField(name: "PaID")
	String paID;
	@JSONField(name: "AC")
	String aC;
	@JSONField(name: "NetMedia")
	String netMedia;
	@JSONField(name: "Renew")
	String renew;
	@JSONField(name: "CharjeType")
	String charjeType;
	@JSONField(name: "ExtraFupTrafic")
	String extraFupTrafic;
	@JSONField(name: "CharjeRoll")
	dynamic charjeRoll;
	@JSONField(name: "IsCard")
	bool isCard;
	@JSONField(name: "FreeNightCredit")
	String freeNightCredit;
	@JSONField(name: "ConvertID")
	String convertID;
	@JSONField(name: "isapprove_ibsname")
	String isapproveIbsname;
	@JSONField(name: "SID")
	String sID;
	@JSONField(name: "OldActive")
	String oldActive;
	@JSONField(name: "NetBillGroup")
	String netBillGroup;
	@JSONField(name: "CanReserve")
	String canReserve;
	@JSONField(name: "ShahkarBypass")
	String shahkarBypass;
	@JSONField(name: "GroupName")
	String groupName;
	@JSONField(name: "IsApprove")
	bool isApprove;
	@JSONField(name: "SpeedControl")
	bool speedControl;
	@JSONField(name: "ClassName")
	String className;
	@JSONField(name: "ClassMonth")
	String classMonth;
}

class ChangeServiceDitailModelResultBank with JsonConvert<ChangeServiceDitailModelResultBank> {
	@JSONField(name: "Serial")
	String serial;
	@JSONField(name: "Name")
	String name;
	@JSONField(name: "Bank")
	String bank;
	@JSONField(name: "Logo")
	String logo;
}

class ChangeServiceDitailModelResultCosts with JsonConvert<ChangeServiceDitailModelResultCosts> {
	int error;
	@JSONField(name: "calc_tax")
	bool calcTax;
	int tax;
	int service;
	int abonman;
	int panel;
	int discount;
	int remain;
	int sum;
	int total;
	@JSONField(name: "ExtraPrice")
	int extraPrice;
	ChangeServiceDitailModelResultCostsChangeinfo changeinfo;
	ChangeServiceDitailModelResultCostsConfirminfo confirminfo;
}

class ChangeServiceDitailModelResultCostsChangeinfo with JsonConvert<ChangeServiceDitailModelResultCostsChangeinfo> {
	@JSONField(name: "ServicePrice")
	int servicePrice;
	@JSONField(name: "PorsantPrice")
	int porsantPrice;
	@JSONField(name: "RealPrice")
	int realPrice;
	@JSONField(name: "ExpDate")
	String expDate;
	@JSONField(name: "Type")
	String type;
	@JSONField(name: "ServiceType")
	String serviceType;
	@JSONField(name: "ServiceName")
	String serviceName;
	@JSONField(name: "ServiceGroupName")
	String serviceGroupName;
	@JSONField(name: "ServiceRef")
	String serviceRef;
	@JSONField(name: "ServiceDate")
	String serviceDate;
	@JSONField(name: "NetType")
	String netType;
	@JSONField(name: "RealServicePrice")
	String realServicePrice;
	@JSONField(name: "ExtraPrice")
	int extraPrice;
	@JSONField(name: "ServiceTypeName")
	String serviceTypeName;
	@JSONField(name: "TotalDays")
	String totalDays;
	@JSONField(name: "RemainDays")
	int remainDays;
	@JSONField(name: "UsedDays")
	int usedDays;
	@JSONField(name: "TotalCredit")
	int totalCredit;
	@JSONField(name: "RealRemainCredit")
	int realRemainCredit;
	@JSONField(name: "UsedCredit")
	int usedCredit;
	@JSONField(name: "IsApprove")
	int isApprove;
	@JSONField(name: "RemainPrice")
	int remainPrice;
	@JSONField(name: "Mabna")
	String mabna;
	@JSONField(name: "0")
	int ziro;
}

class ChangeServiceDitailModelResultCostsConfirminfo with JsonConvert<ChangeServiceDitailModelResultCostsConfirminfo> {
	@JSONField(name: "NewServiceRef")
	String newServiceRef;
	@JSONField(name: "NewServiceName")
	String newServiceName;
	@JSONField(name: "NewServiceGroupName")
	String newServiceGroupName;
	@JSONField(name: "NewType")
	String newType;
	@JSONField(name: "NewServiceType")
	String newServiceType;
	@JSONField(name: "NewGhest")
	String newGhest;
	@JSONField(name: "NewMinPrice")
	dynamic newMinPrice;
	@JSONField(name: "NetType")
	String netType;
	@JSONField(name: "KhesaratPrice")
	int khesaratPrice;
	String methodprice;
	@JSONField(name: "TaxPrice")
	int taxPrice;
	@JSONField(name: "OffPrice")
	int offPrice;
	@JSONField(name: "OffPriceTax")
	int offPriceTax;
	@JSONField(name: "NewPrice")
	int newPrice;
	@JSONField(name: "PayPrice")
	int payPrice;
	@JSONField(name: "PayPriceFinal")
	int payPriceFinal;
	@JSONField(name: "0")

	int ziro;
}
