/// Generated by AssetsRefGenerator on 2020/02/29
class Res {
  static const String IranianSans = "assets/fonts/IranianSans.ttf";
  static const String IRANSansWeb_Medium = "assets/fonts/IRANSansWeb_Medium.woff";
  static const String Samim_FD = "assets/fonts/Samim_FD.ttf";
}
